# Java: "java"
# Bedrock: "bedrock"
# Bedrock mobile reach: "pocket"
# Extends player block interaction reach to match the version specified.
# Note that changes to the attribute minecraft:player.block_interaction_range will not work when this is set to Bedrock or pocket.
player-range-type: "bedrock"

# Java: false
# Bedrock: true
# Note that existing or world generated armor stands are not affected by this configuration at the moment.
enable-arms-on-armor-stands: true

# Java: false
# Bedrock: true
# Disables pressing F to swap item to offhand.
disable-offhand-keybind: true

# Java: false
# Bedrock: true
# Disables pressing numbers to snap item to hotbar.
disable-number-key-inventory-hotkey: true

# Java: false
# Bedrock: true
# Only allows the items that bedrock allows to be in offhand.
bedrock-offhand-items-only: true

# Java: false
# Bedrock: true
# Changes the totem, enchanted golden apple and (not available yet) suspicious stew effects to match Bedrock editions.
bedrock-consumable-effects: true

# Java: false
# Bedrock: true
# Forces the shield to only be blocked when sneaking.
allow-block-only-when-sneaking: true

# Mimics the bedrock coordinates UI by using scoreboard.
show-coordinates: true

# Allows players to toggle coordinates by using /coords
allow-toggling-coordinates: true

# Mimics the bedrock day played UI by using scoreboard.
show-days-played: true

# Allows players to toggle the days played UI by using /coords
allow-toggling-days-played: true
